"""empty message

Revision ID: 03290163f046
Revises: 11feaa270f28
Create Date: 2022-07-01 23:18:07.881925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03290163f046'
down_revision = '11feaa270f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_completed_trades_key', 'user', type_='unique')
    op.drop_constraint('user_lastname_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('user_nationality_key', 'user', type_='unique')
    op.drop_constraint('user_reputation_key', 'user', type_='unique')
    op.drop_constraint('user_score_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_score_key', 'user', ['score'])
    op.create_unique_constraint('user_reputation_key', 'user', ['reputation'])
    op.create_unique_constraint('user_nationality_key', 'user', ['nationality'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_lastname_key', 'user', ['lastname'])
    op.create_unique_constraint('user_completed_trades_key', 'user', ['completed_trades'])
    # ### end Alembic commands ###
