"""empty message

Revision ID: 11feaa270f28
Revises: 3d712f967ee3
Create Date: 2022-06-26 02:03:38.330321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11feaa270f28'
down_revision = '3d712f967ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('completed_trades', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('identification', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('nationality', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('reputation', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['completed_trades'])
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.create_unique_constraint(None, 'user', ['score'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['reputation'])
    op.create_unique_constraint(None, 'user', ['identification'])
    op.create_unique_constraint(None, 'user', ['nationality'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'score')
    op.drop_column('user', 'reputation')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'name')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'identification')
    op.drop_column('user', 'completed_trades')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
