"""empty message

Revision ID: 65e5e50a66ac
Revises: 03290163f046
Create Date: 2022-07-05 16:32:20.477094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e5e50a66ac'
down_revision = '03290163f046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buypublications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=False),
    sa.Column('preferred_banks', sa.String(length=280), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('balance'),
    sa.UniqueConstraint('exchange_rate'),
    sa.UniqueConstraint('message'),
    sa.UniqueConstraint('preferred_banks'),
    sa.UniqueConstraint('status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buypublications')
    # ### end Alembic commands ###
