"""empty message

Revision ID: 6c751e2f6005
Revises: 718980401600
Create Date: 2022-07-05 22:31:51.297803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c751e2f6005'
down_revision = '718980401600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellpublications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=False),
    sa.Column('preferred_banks', sa.String(length=280), nullable=False),
    sa.Column('user_id_pub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_pub'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellpublications')
    # ### end Alembic commands ###
