"""empty message

Revision ID: 718980401600
Revises: 68e0694f73e0
Create Date: 2022-07-05 17:55:25.318818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718980401600'
down_revision = '68e0694f73e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buypublications_balance_key', 'buypublications', type_='unique')
    op.drop_constraint('buypublications_exchange_rate_key', 'buypublications', type_='unique')
    op.drop_constraint('buypublications_message_key', 'buypublications', type_='unique')
    op.drop_constraint('buypublications_preferred_banks_key', 'buypublications', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('buypublications_preferred_banks_key', 'buypublications', ['preferred_banks'])
    op.create_unique_constraint('buypublications_message_key', 'buypublications', ['message'])
    op.create_unique_constraint('buypublications_exchange_rate_key', 'buypublications', ['exchange_rate'])
    op.create_unique_constraint('buypublications_balance_key', 'buypublications', ['balance'])
    # ### end Alembic commands ###
